package util

const (
	DEFAULT = 0
	ADMIN   = 1
)

const (
	PATH_VARIABLE_NOT_FOUND_ERROR_CODE = 1000
	USER_NOT_FOUND_ERROR_CODE          = 1001
	USER_GET_BY_ID_ERROR_CODE          = 1002
	USER_INVALID_POST_BODY_ERROR_CODE  = 1003
	USER_DELETE_BY_ID_ERROR_CODE       = 1004
	USER_VALIDATION_ERROR_CODE         = 1005
)
